### ISSUE TITLE
Deprecate pre-OEP-58 Transifex scripts from all repositories

### ISSUE THREAD

**Issue by OmarIthawi** [openedx/wg-translations#20]
This issue is the final step of the [OEP-58](https://github.com/Zeit-Labs/edx-platform/blob/atlas-proposal/docs/decisions/0019-oep-58-atlas-translations-design.rst) proposal.

It lists all the pull requests that are on hold waiting for the final deprecation approval for the following:

 - Remove direct `tx pull` and `tx push` Transifex commands from repositories
 - Remove in-repository translations in `conf/locale` and `src/i18n/data` from repositories
 - Disable Jenkins @edx-transifex-bot integration
 - Enable the `OPENEDX_ATLAS_PULL` flag permanently.
 - Transifex project resources are marked with `(Deprecated)` in their title.

### Pre-requisites
- [ ] Deprecation ticket created and approved

------

```[tasklist]
### Frontend deprecation pull requests
- [x] Account MFE: openedx/frontend-app-account#887
- [x] Authn MFE: openedx/frontend-app-authn#1085
- [x] Authoring MFE: openedx/frontend-app-course-authoring#627
- [x] Discussion MFE: https://github.com/openedx/frontend-app-discussions/pull/586
- [x] Ecommerce MFE: openedx/frontend-app-ecommerce#341
- [x] Footer: openedx/frontend-component-footer#355
- [x] Gradebook MFE: openedx/frontend-app-gradebook#353
- [x] Header: openedx/frontend-component-header#416
- [x] Learner Dashboard MFE: openedx/frontend-app-learner-dashboard#227
- [x] Learner Record MFE: openedx/frontend-app-learner-record#200
- [x] Learning MFE: openedx/frontend-app-learning#1198
- [x] Library Authoring MFE: openedx/frontend-app-library-authoring#351
- [x] ORA Grading MFE: https://github.com/openedx/frontend-app-ora-grading/pull/278
- [x] Payment MFE: openedx/frontend-app-payment#820
- [x] Portal MFE: openedx/frontend-app-admin-portal#1060
- [x] Profile MFE: openedx/frontend-app-profile#889
- [x] Program Console MFE: openedx/frontend-app-program-console#142
- [x] Studio Frontend MFE: openedx/studio-frontend#383
- [x] Support Tools MFE: https://github.com/openedx/frontend-app-support-tools/pull/361
```

```[tasklist]
### Python deprecation pull requests
- [x] Drag and drop XBlock: https://github.com/openedx/xblock-drag-and-drop-v2/pull/352
- [x] Submit and Compare XBlock: https://github.com/openedx/xblock-submit-and-compare/pull/146
- [x] Image Explorer XBlock: https://github.com/openedx/xblock-image-explorer/pull/112
- [x] Free Text Response XBlock: https://github.com/openedx/xblock-free-text-response/pull/157
- [x] Recommender XBlock: https://github.com/openedx/RecommenderXBlock/pull/77
```

**Comment by OmarIthawi** [comment]
I'm wondering if this should live in the public roadmap https://github.com/orgs/openedx/projects/4/views/1 board

**Comment by OmarIthawi** [comment]
Closed! Completed.
